### ISSUE TITLE
the array returned by query() contains duplicate numbers prepended with a space

### ISSUE THREAD

**Issue by kculbert** [rpcme/Net-Gnats#1]
The 2nd and 3rd elements are duplicates and have spaces (although they don't show up here).

my $PRs = $gnats->query("\(product == \"sbrcarrier\" & responsible == \"kculbert\" & state != \"closed\" \)");

#query now returns an anonymous array
if (defined $PRs)
{
    print "Found PRs:\n" . join("\n", @$PRs ) . "\n";
} else {
    print "no PRs matched";
}

Found PRs:
852049
 852049
 852049
861700
928215
936990
937751
938098
940077
959984
969952
989057
1036136

**Comment by rpcme** [comment]
Hello,

the query() method takes an array of expressions.  For example:
```perl
$gnats->query("product = \"sbrcarrier\"",
              "responsible = \"kculbert\"",
              "state != \"closed\"";
```

In gnats, these are naturally "ANDed" together.  It's not quite like query-pr (the gnats utility) where you specify the &'s.

Also, for a correct list of operators, please see section 2.4.3 of the gnats manual.  But it might be good to document it in the perl module.
http://www.gnu.org/software/gnats/doc/gnats-4.2.0/gnats.html

Once corrected, please let me know.  It's super surprising to see duplicates -- it means you would have PR's coming back from Gnats with duplicate Number fields!

**Comment by kculbert** [comment]
using an array returned a null reference
my $PRs = $gnats->query("product == \"sbrcarrier\"",
                         "responsible == \"kculbert\"",
                         "state != \"closed\"");

**Comment by rpcme** [comment]
One issue is right now it's returning zero if there is an error, not an empty set.  This is a problem and will be fixed.  Also, it's pretty obvious this module needs a query builder because it's pretty obnoxious that you have to remember gnats formatting. I will make this a bug due to what it's returning, and make an enhancement for a query builder.

However, your expressions have errors.
1) make it so the strings do not interpolate.
2) do not add spaces between name and value.

Please see:
```perl
#! /usr/bin/env perl
use strictures;
use 5.10.00;
use Net::Gnats;

my ($list) = @_;
my $g = Net::Gnats->new('192.168.1.203','1529');
$g->gnatsd_connect;
$g->login('default', 'madmin', 'madmin');

$list = $g->query('Number="10"');
say 'Should return all numbered prs starting with 10';
say ref $list eq 'ARRAY' ? join ' ', @$list : 'No results.';

# query is malformed - no results.
$list = $g->query('Number = "10"');
say 'Should return all numbered prs starting with 10';
say ref $list eq 'ARRAY' ? join ' ', @$list : 'No results.';

$list = $g->query('Number=="10"');
say 'Should return single pr 10';
say ref $list eq 'ARRAY' ? join ' ', @$list : 'No results.';

$list = $g->query('Number="100000"');
say 'Should return no results';
say ref $list eq 'ARRAY' ? join ' ', @$list : 'No results.';

# field names are not case sensitive when querying
$list = $g->query('number=="10"');
say 'Should return single pr 10';
say ref $list eq 'ARRAY' ? join ' ', @$list : 'No results.';

```

**Comment by kculbert** [comment]
my $PRs = $gnats->query('product=="sbrcarrier"','responsible=="kculbert"');
does not work and returns immediately, but 
my $PRs = $gnats->query('product=="sbrcarrier" & responsible=="kculbert"'); 
does work

**Comment by rpcme** [comment]
Okay I know now what happened.

This used to be multiple EXPR calls, and then I lumped them all into one.  When I did that, I didn’t add the &.  This is what I get for trying to be efficient.

I will fix this, ok?  It will do the correct thing with the ‘&’ in the expression.
