### ISSUE TITLE
PR->getField throws exception

### ISSUE THREAD

**Issue by kculbert** [rpcme/Net-Gnats#2]
asString() works fine, getField() doesn't

my $pra = $PRs;
foreach my $iter ( 0 .. $#$pra ) {
    my $pr = $pra->[$iter];
    if ($pr =~ /\A /)
    {
        next;
    }
    print "Getting PR$pr\n";

    my $PR = $gnats->get_pr_by_number($pr);
    my $responsible = "";
    my $counter = 1;
    my $state = "";
    print $PR->asString();

    my $originator = $PR->getField("Originator{$counter}");
}

Can't call method "value" on an undefined value at
        C:/strawberry/perl/site/lib/Net/Gnats/PR.pm line 136, <GEN0> line 5957 (#1)
    (F) You used the syntax of a method call, but the slot filled by the
    object reference or package name contains an undefined value.  Something
    like this will reproduce the error:

        $BADREF = undef;
        process $BADREF 1,2,3;
        $BADREF->process(1,2,3);

Uncaught exception from user code:
        Can't call method "value" on an undefined value at C:/strawberry/perl/site/lib/Net/Gnats/PR.pm line 136, <GEN0> line
5957.
        Net::Gnats::PR::getField('Net::Gnats::PR=HASH(0x2d2ef80)', 'Originator{1}') called at change_responsible.pr line 71

**Comment by rpcme** [comment]
quite frankly I never liked getField -- that's why I added get_field to work with the new FieldInstance class.

In any case, I am unsure you would have a field named Originator{1} or Originator{2} or so forth?

maybe it should just be $PR->getField("Originator");?

However, I do accept that it could return undef if the field doesn't exist. (however, in general this method causes problems because there will be cases where undef may be an appropriate value for a given datatype).

**Comment by kculbert** [comment]
I tried with only "Originator" and it didn't make a difference.  Originator is a scoped field:
>Originator{1}:  jfrantz
getField("Synopsis"), which is non-scoped, works; getField("Blocker{1}") doesn't.

**Comment by kculbert** [comment]
closed by fat fingers

**Comment by rpcme** [comment]
What is a scoped field?  I can't find it anywhere in the Gnats specification.  I am only familiar with what's in the specification, and making site-specific customizations.

Is this something your organization created?  Orgs can obviously customize gnats, but I wouldn't be aware of out-of-spec customizations.

if you could add this at the beginning of your script and send me **in email** the output it would be helpful.

```perl
Net::Gnats->verbose(1);
Net::Gnats->verbose_level(3);
```

It will give me the information I need.  Also, if your admin could give you the gnats database **dbconfig** file, and you send me that as well (without any secret information) it will help me understand what this field is.

**Comment by kculbert** [comment]
Scopes are equivalent to branches; some fields can have an entry per scope, such as responsible or state.  These fields are indexed using {}.   Other fields have only a single entry, such as synopsis.
I'll ask for the dbconfig.
I've sent the verbose file and also the asString() output.

**Comment by rpcme** [comment]
Were you able to get the dbconfig?

I would like to get this issue closed asap, thanks!

**Comment by rpcme** [comment]
Added scopes capability.
