### ISSUE TITLE
files missing in kit

### ISSUE THREAD

**Issue by kculbert** [rpcme/Net-Gnats#3]
D:\Dwimperl\perl\lib\Net-Gnats-0.15>perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        t/gnats_general.t
        t/test.t
Please inform the author.
Writing Makefile for Net::Gnats
Writing MYMETA.yml and MYMETA.json

**Comment by rpcme** [comment]
Hello,

This was fixed in 0.17.which was released this morning.  With that release, I also added the ->send method to PR.pm, where sending a PR actually persists the number field (surprisingly, this was never in the module).

**Comment by kculbert** [comment]
0.17 ok
